"""

Revision ID: 04bb63621bf1
Revises: 250b87dde449
Create Date: 2025-06-07 10:03:34.622286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04bb63621bf1'
down_revision = '250b87dde449'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasklist', sa.Column('strategy_keys_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasklist', 'strategy_keys_id')
    # ### end Alembic commands ###
