"""

Revision ID: 070a4abaf019
Revises: 1fb8c8dc58e3
Create Date: 2025-06-04 15:28:29.866790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070a4abaf019'
down_revision = '1fb8c8dc58e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_entrusts_is_mock'), 'entrusts', ['is_mock'], unique=False)
    op.create_index(op.f('ix_orders_is_mock'), 'orders', ['is_mock'], unique=False)
    op.create_index(op.f('ix_positions_is_mock'), 'positions', ['is_mock'], unique=False)
    op.create_index(op.f('ix_trades_is_mock'), 'trades', ['is_mock'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_is_mock'), table_name='trades')
    op.drop_index(op.f('ix_positions_is_mock'), table_name='positions')
    op.drop_index(op.f('ix_orders_is_mock'), table_name='orders')
    op.drop_index(op.f('ix_entrusts_is_mock'), table_name='entrusts')
    # ### end Alembic commands ###
