"""

Revision ID: 07ab3e87c195
Revises: 1a69ebe0c486
Create Date: 2025-11-14 15:13:38.511046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07ab3e87c195'
down_revision = '1a69ebe0c486'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasklist', sa.Column('position_ratio', sa.Numeric(), server_default='1', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasklist', 'position_ratio')
    # ### end Alembic commands ###
