"""

Revision ID: 082422ec7ccb
Revises: fb407105710b
Create Date: 2025-06-09 12:08:38.775190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '082422ec7ccb'
down_revision = 'fb407105710b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('logger_name', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('module', sa.String(), nullable=True),
    sa.Column('func_name', sa.String(), nullable=True),
    sa.Column('line_num', sa.Integer(), nullable=True),
    sa.Column('exception', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logger')
    # ### end Alembic commands ###
