"""

Revision ID: 09f54fab8f5b
Revises: c973f5f9682c
Create Date: 2025-06-06 12:34:42.564214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09f54fab8f5b'
down_revision = 'c973f5f9682c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('task_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'task_id')
    # ### end Alembic commands ###
