"""

Revision ID: 0beac3d413f5
Revises: 665c2306314e
Create Date: 2025-05-30 14:10:39.301346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0beac3d413f5'
down_revision = '665c2306314e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasklist', sa.Column('service_charge', sa.Numeric(), nullable=True))
    op.add_column('tasklist', sa.Column('lower_limit_of_fees', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasklist', 'lower_limit_of_fees')
    op.drop_column('tasklist', 'service_charge')
    # ### end Alembic commands ###
