"""

Revision ID: 0c14bb355caa
Revises: 98f4f321d568
Create Date: 2025-06-03 11:51:51.649985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c14bb355caa'
down_revision = '98f4f321d568'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('stock_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'stock_code')
    # ### end Alembic commands ###
