"""

Revision ID: 0cd5bf054f8d
Revises: d358634f863f
Create Date: 2025-06-05 10:46:07.013566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cd5bf054f8d'
down_revision = 'd358634f863f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
