"""

Revision ID: 15582046f382
Revises: b43147be6240
Create Date: 2025-05-20 17:23:52.426696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15582046f382'
down_revision = 'b43147be6240'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entrusts',
    sa.Column('traded_amount', sa.Numeric(), nullable=True),
    sa.Column('traded_price', sa.Numeric(), nullable=True),
    sa.Column('stock_code', sa.String(), nullable=True),
    sa.Column('traded_volume', sa.Numeric(), nullable=True),
    sa.Column('traded_time', sa.Integer(), nullable=True),
    sa.Column('traded_id', sa.String(), nullable=True),
    sa.Column('status_msg', sa.String(), nullable=True),
    sa.Column('orders_id', sa.Integer(), nullable=True),
    sa.Column('order_type', sa.Integer(), nullable=True),
    sa.Column('price_type', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('order_status', sa.Integer(), nullable=True),
    sa.Column('order_sysid', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), server_default='0', nullable=True),
    sa.Column('offset_flag', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('security_code', sa.String(), nullable=True),
    sa.Column('fix_result_order_id', sa.String(), nullable=True),
    sa.Column('style', sa.String(), nullable=True),
    sa.Column('run_params', sa.String(), nullable=True),
    sa.Column('pindex', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('is_buy', sa.Integer(), server_default='0', nullable=True),
    sa.Column('strategy_code', sa.String(), nullable=True),
    sa.Column('add_time', sa.String(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('avg_cost', sa.Numeric(), nullable=True),
    sa.Column('status_msg', sa.String(), nullable=True),
    sa.Column('commission', sa.Numeric(), nullable=True),
    sa.Column('status', sa.Integer(), server_default='0', nullable=True),
    sa.Column('transaction_status', sa.Integer(), server_default='0', nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setting',
    sa.Column('python_path', sa.String(), nullable=True),
    sa.Column('mini_qmt_path', sa.String(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('salt', sa.String(), nullable=True),
    sa.Column('server_url', sa.String(), nullable=True),
    sa.Column('run_model_type', sa.Integer(), server_default='0', nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasklist',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('strategy_code', sa.String(), nullable=True),
    sa.Column('order_count_type', sa.Integer(), nullable=True),
    sa.Column('strategy_amount', sa.Integer(), nullable=True),
    sa.Column('allocation_amount', sa.Integer(), nullable=True),
    sa.Column('enable', sa.Integer(), server_default='1', nullable=True),
    sa.Column('days_number', sa.Integer(), nullable=True),
    sa.Column('is_open', sa.Integer(), server_default='0', nullable=True),
    sa.Column('delete_time', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('order_sysid', sa.String(), nullable=True),
    sa.Column('order_time', sa.Integer(), nullable=True),
    sa.Column('order_volume', sa.Integer(), nullable=True),
    sa.Column('price_type', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('traded_volume', sa.Numeric(), nullable=True),
    sa.Column('traded_price', sa.Numeric(), nullable=True),
    sa.Column('order_status', sa.Integer(), nullable=True),
    sa.Column('status_msg', sa.String(), nullable=True),
    sa.Column('offset_flag', sa.Integer(), nullable=True),
    sa.Column('orders_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), server_default='0', nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_table('tasklist')
    op.drop_table('setting')
    op.drop_table('orders')
    op.drop_table('entrusts')
    # ### end Alembic commands ###
