"""

Revision ID: 16f1389120c2
Revises: d5ea964b3b9d
Create Date: 2025-06-12 08:53:41.500961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16f1389120c2'
down_revision = 'd5ea964b3b9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('commission', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'commission')
    # ### end Alembic commands ###
