"""

Revision ID: 19ff43303ec2
Revises: 5f389173a5d8
Create Date: 2025-06-04 10:30:53.451850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19ff43303ec2'
down_revision = '5f389173a5d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
