"""

Revision ID: 1a69ebe0c486
Revises: 6badaf17893b
Create Date: 2025-10-31 15:50:23.237493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a69ebe0c486'
down_revision = '6badaf17893b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
