"""

Revision ID: 1a94dda4fa31
Revises: 21145e871673
Create Date: 2025-06-07 10:12:37.819739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a94dda4fa31'
down_revision = '21145e871673'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasklist', sa.Column('host_user_email', sa.String(), nullable=True))
    op.add_column('tasklist', sa.Column('strategy_key_id', sa.Integer(), nullable=True))
    op.drop_column('tasklist', 'come_form_str')
    op.drop_column('tasklist', 'strategy_keys_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasklist', sa.Column('strategy_keys_id', sa.INTEGER(), nullable=True))
    op.add_column('tasklist', sa.Column('come_form_str', sa.VARCHAR(), nullable=True))
    op.drop_column('tasklist', 'strategy_key_id')
    op.drop_column('tasklist', 'host_user_email')
    # ### end Alembic commands ###
