"""

Revision ID: 1aa18a798069
Revises: 5c506eb4d39e
Create Date: 2025-05-23 10:05:54.474139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aa18a798069'
down_revision = '5c506eb4d39e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('setting', sa.Column('auto_buy_stock_ipo', sa.Integer(), server_default='0', nullable=True))
    op.add_column('setting', sa.Column('auto_buy_purchase_ipo', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('setting', 'auto_buy_purchase_ipo')
    op.drop_column('setting', 'auto_buy_stock_ipo')
    # ### end Alembic commands ###
