"""

Revision ID: 1dfc206b5893
Revises: 07ab3e87c195
Create Date: 2025-11-14 16:21:52.343960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dfc206b5893'
down_revision = '07ab3e87c195'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasklist', sa.Column('open_mandatory_limit_order', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasklist', 'open_mandatory_limit_order')
    # ### end Alembic commands ###
