"""

Revision ID: 1f921a4f9c15
Revises: 9b3c8e5abf11
Create Date: 2025-05-24 15:42:02.924655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f921a4f9c15'
down_revision = '9b3c8e5abf11'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
    sa.Column('security_code', sa.String(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tasklist', sa.Column('position_amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasklist', 'position_amount')
    op.drop_table('position')
    # ### end Alembic commands ###
