"""

Revision ID: 1fb8c8dc58e3
Revises: 19ff43303ec2
Create Date: 2025-06-04 15:18:55.730699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb8c8dc58e3'
down_revision = '19ff43303ec2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entrusts', sa.Column('is_mock', sa.Integer(), server_default='0', nullable=True))
    op.add_column('orders', sa.Column('is_mock', sa.Integer(), server_default='0', nullable=True))
    op.add_column('positions', sa.Column('is_mock', sa.Integer(), server_default='0', nullable=True))
    op.add_column('trades', sa.Column('is_mock', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'is_mock')
    op.drop_column('positions', 'is_mock')
    op.drop_column('orders', 'is_mock')
    op.drop_column('entrusts', 'is_mock')
    # ### end Alembic commands ###
