"""

Revision ID: 21145e871673
Revises: 04bb63621bf1
Create Date: 2025-06-07 10:08:50.714124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21145e871673'
down_revision = '04bb63621bf1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
