"""

Revision ID: 250b87dde449
Revises: a5f04056d6dd
Create Date: 2025-06-06 15:25:26.130703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250b87dde449'
down_revision = 'a5f04056d6dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasklist', sa.Column('come_form_str', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasklist', 'come_form_str')
    # ### end Alembic commands ###
