"""

Revision ID: 2f7dcb98dbdc
Revises: 082422ec7ccb
Create Date: 2025-06-09 12:39:28.101225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f7dcb98dbdc'
down_revision = '082422ec7ccb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
