"""

Revision ID: 2fa8af85fa19
Revises: dac0eafcee97
Create Date: 2025-05-31 23:45:28.866306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa8af85fa19'
down_revision = 'dac0eafcee97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest', sa.Column('state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest', 'state')
    # ### end Alembic commands ###
