"""

Revision ID: 423724d7bf7f
Revises: cb83aa7a9d58
Create Date: 2025-06-17 21:27:58.667243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '423724d7bf7f'
down_revision = 'cb83aa7a9d58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('setting', sa.Column('ths_path', sa.String(), nullable=True))
    op.add_column('setting', sa.Column('ths_pwd', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('setting', 'ths_pwd')
    op.drop_column('setting', 'ths_path')
    # ### end Alembic commands ###
