"""

Revision ID: 4440b066fce2
Revises: 98bd86d5740d
Create Date: 2025-07-07 21:57:40.280621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4440b066fce2'
down_revision = '98bd86d5740d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
