"""

Revision ID: 4b30d3ff9ca0
Revises: cf01b55a1307
Create Date: 2025-06-03 15:11:03.784800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b30d3ff9ca0'
down_revision = 'cf01b55a1307'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
