"""

Revision ID: 523683b9b2e8
Revises: b0aeb5a4cef5
Create Date: 2025-05-21 12:57:22.164078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '523683b9b2e8'
down_revision = 'b0aeb5a4cef5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
