"""

Revision ID: 529782e3dade
Revises: 2fa8af85fa19
Create Date: 2025-06-02 17:30:02.973908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529782e3dade'
down_revision = '2fa8af85fa19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest', 'start_time')
    op.add_column('positions', sa.Column('delete_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'delete_time')
    op.add_column('backtest', sa.Column('start_time', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
