"""

Revision ID: 532942a6e3c4
Revises: 1f921a4f9c15
Create Date: 2025-05-24 15:50:46.024288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '532942a6e3c4'
down_revision = '1f921a4f9c15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('positions',
    sa.Column('security_code', sa.String(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('position')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
    sa.Column('security_code', sa.VARCHAR(), nullable=True),
    sa.Column('volume', sa.INTEGER(), nullable=True),
    sa.Column('amount', sa.NUMERIC(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('positions')
    # ### end Alembic commands ###
