"""

Revision ID: 549dea92950f
Revises: 0cd5bf054f8d
Create Date: 2025-06-05 21:51:19.592893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '549dea92950f'
down_revision = '0cd5bf054f8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest', sa.Column('order_count_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest', 'order_count_type')
    # ### end Alembic commands ###
