"""

Revision ID: 560b1c57f776
Revises: f8a587fd9552
Create Date: 2025-06-12 14:36:32.029963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560b1c57f776'
down_revision = 'f8a587fd9552'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasklist', sa.Column('is_simulation', sa.Integer(), server_default='0', nullable=True))
    op.add_column('trades', sa.Column('commission', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'commission')
    op.drop_column('tasklist', 'is_simulation')
    # ### end Alembic commands ###
