"""

Revision ID: 5c506eb4d39e
Revises: 523683b9b2e8
Create Date: 2025-05-22 22:34:11.812890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c506eb4d39e'
down_revision = '523683b9b2e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('setting', sa.Column('auto_national_debt', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('setting', 'auto_national_debt')
    # ### end Alembic commands ###
