"""

Revision ID: 5f389173a5d8
Revises: b0ec1d0d11aa
Create Date: 2025-06-04 10:04:59.743526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f389173a5d8'
down_revision = 'b0ec1d0d11aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasklist', sa.Column('mock_allocation_amount', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasklist', 'mock_allocation_amount')
    # ### end Alembic commands ###
