"""

Revision ID: 61f020288394
Revises: 895b0cf90a97
Create Date: 2025-06-04 23:52:32.250249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61f020288394'
down_revision = '895b0cf90a97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('positions', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'positions')
    # ### end Alembic commands ###
