"""

Revision ID: 665c2306314e
Revises: 532942a6e3c4
Create Date: 2025-05-29 23:13:48.365741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665c2306314e'
down_revision = '532942a6e3c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('setting', sa.Column('auto_startup', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('setting', 'auto_startup')
    # ### end Alembic commands ###
