"""

Revision ID: 84093fc6bb19
Revises: a4f715ab4b80
Create Date: 2025-05-31 00:43:16.098758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84093fc6bb19'
down_revision = 'a4f715ab4b80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('service_charge', sa.Numeric(), nullable=True),
    sa.Column('initial_amount', sa.Numeric(), nullable=True),
    sa.Column('final_amount', sa.Numeric(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tasklist', sa.Column('backtest_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasklist', 'backtest_id')
    op.drop_table('backtest')
    # ### end Alembic commands ###
