"""

Revision ID: 893f6c585cd2
Revises: a681e6d08085
Create Date: 2025-05-20 17:19:31.791241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '893f6c585cd2'
down_revision = 'a681e6d08085'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ppx_storage_var', sa.Column('remark2', sa.String(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ppx_storage_var', 'remark2')
    # ### end Alembic commands ###
