"""

Revision ID: 895b0cf90a97
Revises: aa39b00cc416
Create Date: 2025-06-04 16:26:51.525091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '895b0cf90a97'
down_revision = 'aa39b00cc416'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('average_price', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'average_price')
    # ### end Alembic commands ###
