"""

Revision ID: 98bd86d5740d
Revises: fa5bf4cff82d
Create Date: 2025-07-07 20:11:27.340143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98bd86d5740d'
down_revision = 'fa5bf4cff82d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('tasklist', sa.Column('platform', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('tasklist', 'platform')
    # ### end Alembic commands ###
    pass
