"""

Revision ID: 98f4f321d568
Revises: e0c2edd701ce
Create Date: 2025-06-02 17:56:56.752835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98f4f321d568'
down_revision = 'e0c2edd701ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('order_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'order_type')
    # ### end Alembic commands ###
