"""

Revision ID: 99e3e584e08e
Revises: 99e6760588e6
Create Date: 2025-06-09 21:03:06.116165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e3e584e08e'
down_revision = '99e6760588e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_table_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.String(), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('record_type', sa.Integer(), nullable=True),
    sa.Column('record_time', sa.Integer(), nullable=True),
    sa.Column('record_content', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_trade_date_hist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('data_all_stocks', sa.Column('total_market_value', sa.Numeric(), nullable=True))
    op.add_column('data_all_stocks', sa.Column('circulating_market_value', sa.Numeric(), nullable=True))
    op.add_column('data_all_stocks', sa.Column('rise_speed', sa.Numeric(), nullable=True))
    op.add_column('data_all_stocks', sa.Column('five_minute_change', sa.Numeric(), nullable=True))
    op.add_column('data_all_stocks', sa.Column('sixty_days_change', sa.Numeric(), nullable=True))
    op.add_column('data_all_stocks', sa.Column('year_to_date_change', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_all_stocks', 'year_to_date_change')
    op.drop_column('data_all_stocks', 'sixty_days_change')
    op.drop_column('data_all_stocks', 'five_minute_change')
    op.drop_column('data_all_stocks', 'rise_speed')
    op.drop_column('data_all_stocks', 'circulating_market_value')
    op.drop_column('data_all_stocks', 'total_market_value')
    op.drop_table('data_trade_date_hist')
    op.drop_table('data_table_record')
    # ### end Alembic commands ###
