"""

Revision ID: 99e6760588e6
Revises: 0added726d5e
Create Date: 2025-06-09 16:35:15.677901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e6760588e6'
down_revision = '0added726d5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_all_stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('latest_price', sa.Numeric(), nullable=True),
    sa.Column('change_rate', sa.Numeric(), nullable=True),
    sa.Column('change_amount', sa.Numeric(), nullable=True),
    sa.Column('volume', sa.Numeric(), nullable=True),
    sa.Column('turnover', sa.Numeric(), nullable=True),
    sa.Column('amplitude', sa.Numeric(), nullable=True),
    sa.Column('highest', sa.Numeric(), nullable=True),
    sa.Column('lowest', sa.Numeric(), nullable=True),
    sa.Column('open', sa.Numeric(), nullable=True),
    sa.Column('close', sa.Numeric(), nullable=True),
    sa.Column('volume_ratio', sa.Numeric(), nullable=True),
    sa.Column('turnover_ratio', sa.Numeric(), nullable=True),
    sa.Column('pe_dynamic', sa.Numeric(), nullable=True),
    sa.Column('pb', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_st_stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('latest_price', sa.Numeric(), nullable=True),
    sa.Column('change_rate', sa.Numeric(), nullable=True),
    sa.Column('change_amount', sa.Numeric(), nullable=True),
    sa.Column('volume', sa.Numeric(), nullable=True),
    sa.Column('turnover', sa.Numeric(), nullable=True),
    sa.Column('amplitude', sa.Numeric(), nullable=True),
    sa.Column('highest', sa.Numeric(), nullable=True),
    sa.Column('lowest', sa.Numeric(), nullable=True),
    sa.Column('open', sa.Numeric(), nullable=True),
    sa.Column('close', sa.Numeric(), nullable=True),
    sa.Column('volume_ratio', sa.Numeric(), nullable=True),
    sa.Column('turnover_ratio', sa.Numeric(), nullable=True),
    sa.Column('pe_dynamic', sa.Numeric(), nullable=True),
    sa.Column('pb', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('stockdata_all_stocks')
    op.drop_table('stockdata_st_stocks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stockdata_st_stocks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('latest_price', sa.NUMERIC(), nullable=True),
    sa.Column('change_rate', sa.NUMERIC(), nullable=True),
    sa.Column('change_amount', sa.NUMERIC(), nullable=True),
    sa.Column('volume', sa.NUMERIC(), nullable=True),
    sa.Column('turnover', sa.NUMERIC(), nullable=True),
    sa.Column('amplitude', sa.NUMERIC(), nullable=True),
    sa.Column('highest', sa.NUMERIC(), nullable=True),
    sa.Column('lowest', sa.NUMERIC(), nullable=True),
    sa.Column('open', sa.NUMERIC(), nullable=True),
    sa.Column('close', sa.NUMERIC(), nullable=True),
    sa.Column('volume_ratio', sa.NUMERIC(), nullable=True),
    sa.Column('turnover_ratio', sa.NUMERIC(), nullable=True),
    sa.Column('pe_dynamic', sa.NUMERIC(), nullable=True),
    sa.Column('pb', sa.NUMERIC(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stockdata_all_stocks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('latest_price', sa.NUMERIC(), nullable=True),
    sa.Column('change_rate', sa.NUMERIC(), nullable=True),
    sa.Column('change_amount', sa.NUMERIC(), nullable=True),
    sa.Column('volume', sa.NUMERIC(), nullable=True),
    sa.Column('turnover', sa.NUMERIC(), nullable=True),
    sa.Column('amplitude', sa.NUMERIC(), nullable=True),
    sa.Column('highest', sa.NUMERIC(), nullable=True),
    sa.Column('lowest', sa.NUMERIC(), nullable=True),
    sa.Column('open', sa.NUMERIC(), nullable=True),
    sa.Column('close', sa.NUMERIC(), nullable=True),
    sa.Column('volume_ratio', sa.NUMERIC(), nullable=True),
    sa.Column('turnover_ratio', sa.NUMERIC(), nullable=True),
    sa.Column('pe_dynamic', sa.NUMERIC(), nullable=True),
    sa.Column('pb', sa.NUMERIC(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('data_st_stocks')
    op.drop_table('data_all_stocks')
    # ### end Alembic commands ###
