"""

Revision ID: 9b3c8e5abf11
Revises: 1aa18a798069
Create Date: 2025-05-23 10:42:50.870328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b3c8e5abf11'
down_revision = '1aa18a798069'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('setting', sa.Column('account', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('setting', 'account')
    # ### end Alembic commands ###
