"""

Revision ID: 9b65683001b8
Revises: 
Create Date: 2025-10-26 23:02:36.675677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b65683001b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('is_connected', sa.Integer(), nullable=True),
    sa.Column('is_main', sa.Integer(), nullable=True),
    sa.Column('mini_qmt_path', sa.String(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('client_type', sa.Integer(), nullable=True),
    sa.Column('ths_path', sa.String(), nullable=True),
    sa.Column('ths_client_id', sa.String(), nullable=True),
    sa.Column('ths_pwd', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backtest',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('order_count_type', sa.Integer(), nullable=True),
    sa.Column('service_charge', sa.Numeric(), nullable=True),
    sa.Column('accruing_amounts', sa.Numeric(), nullable=True),
    sa.Column('initial_capital', sa.Numeric(), nullable=True),
    sa.Column('lower_limit_of_fees', sa.Numeric(), nullable=True),
    sa.Column('final_amount', sa.Numeric(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('can_use_amount', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_all_stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('latest_price', sa.Numeric(), nullable=True),
    sa.Column('change_rate', sa.Numeric(), nullable=True),
    sa.Column('change_amount', sa.Numeric(), nullable=True),
    sa.Column('volume', sa.Numeric(), nullable=True),
    sa.Column('turnover', sa.Numeric(), nullable=True),
    sa.Column('amplitude', sa.Numeric(), nullable=True),
    sa.Column('highest', sa.Numeric(), nullable=True),
    sa.Column('lowest', sa.Numeric(), nullable=True),
    sa.Column('open', sa.Numeric(), nullable=True),
    sa.Column('close', sa.Numeric(), nullable=True),
    sa.Column('volume_ratio', sa.Numeric(), nullable=True),
    sa.Column('turnover_ratio', sa.Numeric(), nullable=True),
    sa.Column('pe_dynamic', sa.Numeric(), nullable=True),
    sa.Column('pb', sa.Numeric(), nullable=True),
    sa.Column('total_market_value', sa.Numeric(), nullable=True),
    sa.Column('circulating_market_value', sa.Numeric(), nullable=True),
    sa.Column('rise_speed', sa.Numeric(), nullable=True),
    sa.Column('five_minute_change', sa.Numeric(), nullable=True),
    sa.Column('sixty_days_change', sa.Numeric(), nullable=True),
    sa.Column('year_to_date_change', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_st_stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('latest_price', sa.Numeric(), nullable=True),
    sa.Column('change_rate', sa.Numeric(), nullable=True),
    sa.Column('change_amount', sa.Numeric(), nullable=True),
    sa.Column('volume', sa.Numeric(), nullable=True),
    sa.Column('turnover', sa.Numeric(), nullable=True),
    sa.Column('amplitude', sa.Numeric(), nullable=True),
    sa.Column('highest', sa.Numeric(), nullable=True),
    sa.Column('lowest', sa.Numeric(), nullable=True),
    sa.Column('open', sa.Numeric(), nullable=True),
    sa.Column('close', sa.Numeric(), nullable=True),
    sa.Column('volume_ratio', sa.Numeric(), nullable=True),
    sa.Column('turnover_ratio', sa.Numeric(), nullable=True),
    sa.Column('pe_dynamic', sa.Numeric(), nullable=True),
    sa.Column('pb', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_table_record',
    sa.Column('table_name', sa.String(), nullable=True),
    sa.Column('record_type', sa.Integer(), nullable=True),
    sa.Column('record_time', sa.String(), nullable=True),
    sa.Column('record_content', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_trade_date_hist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entrusts',
    sa.Column('traded_amount', sa.Numeric(), nullable=True),
    sa.Column('traded_price', sa.Numeric(), nullable=True),
    sa.Column('stock_code', sa.String(), nullable=True),
    sa.Column('traded_volume', sa.Numeric(), nullable=True),
    sa.Column('traded_time', sa.Integer(), nullable=True),
    sa.Column('traded_id', sa.String(), nullable=True),
    sa.Column('status_msg', sa.String(), nullable=True),
    sa.Column('orders_id', sa.Integer(), nullable=True),
    sa.Column('order_type', sa.Integer(), nullable=True),
    sa.Column('price_type', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('order_status', sa.Integer(), nullable=True),
    sa.Column('order_sysid', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), server_default='0', nullable=True),
    sa.Column('offset_flag', sa.Integer(), nullable=True),
    sa.Column('backtest_id', sa.Integer(), nullable=True),
    sa.Column('is_mock', sa.Integer(), server_default='0', nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entrusts_is_mock'), 'entrusts', ['is_mock'], unique=False)
    op.create_table('logger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('logger_name', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('module', sa.String(), nullable=True),
    sa.Column('func_name', sa.String(), nullable=True),
    sa.Column('line_num', sa.Integer(), nullable=True),
    sa.Column('exception', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('security_code', sa.String(), nullable=True),
    sa.Column('fix_result_order_id', sa.String(), nullable=True),
    sa.Column('style', sa.String(), nullable=True),
    sa.Column('run_params', sa.String(), nullable=True),
    sa.Column('pindex', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('is_buy', sa.Integer(), server_default='0', nullable=True),
    sa.Column('strategy_code', sa.String(), nullable=True),
    sa.Column('add_time', sa.String(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('avg_cost', sa.Numeric(), nullable=True),
    sa.Column('status_msg', sa.String(), nullable=True),
    sa.Column('commission', sa.Numeric(), nullable=True),
    sa.Column('status', sa.Integer(), server_default='0', nullable=True),
    sa.Column('transaction_status', sa.Integer(), server_default='0', nullable=True),
    sa.Column('backtest_id', sa.Integer(), nullable=True),
    sa.Column('positions', sa.String(), nullable=True),
    sa.Column('is_mock', sa.Integer(), server_default='0', nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_is_mock'), 'orders', ['is_mock'], unique=False)
    op.create_table('positions',
    sa.Column('security_code', sa.String(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('average_price', sa.Numeric(), nullable=True),
    sa.Column('backtest_id', sa.Integer(), nullable=True),
    sa.Column('delete_time', sa.DateTime(), nullable=True),
    sa.Column('is_mock', sa.Integer(), server_default='0', nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_is_mock'), 'positions', ['is_mock'], unique=False)
    op.create_table('ppx_storage_var',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('val', sa.String(), server_default='', nullable=False),
    sa.Column('remark', sa.String(), server_default='', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ppx_storage_var_key'), 'ppx_storage_var', ['key'], unique=False)
    op.create_table('setting',
    sa.Column('python_path', sa.String(), nullable=True),
    sa.Column('mini_qmt_path', sa.String(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('salt', sa.String(), nullable=True),
    sa.Column('server_url', sa.String(), nullable=True),
    sa.Column('run_model_type', sa.Integer(), server_default='0', nullable=True),
    sa.Column('auto_national_debt', sa.Integer(), server_default='0', nullable=True),
    sa.Column('auto_buy_stock_ipo', sa.Integer(), server_default='0', nullable=True),
    sa.Column('auto_buy_purchase_ipo', sa.Integer(), server_default='0', nullable=True),
    sa.Column('auto_reorder', sa.Integer(), server_default='0', nullable=True),
    sa.Column('auto_startup', sa.Integer(), server_default='0', nullable=True),
    sa.Column('account', sa.String(), nullable=True),
    sa.Column('client_type', sa.Integer(), server_default='1', nullable=True),
    sa.Column('ths_path', sa.String(), nullable=True),
    sa.Column('ths_pwd', sa.String(), nullable=True),
    sa.Column('ths_client_id', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasklist',
    sa.Column('task_type', sa.Integer(), server_default='1', nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('host_user_email', sa.String(), nullable=True),
    sa.Column('share_secret', sa.String(), nullable=True),
    sa.Column('strategy_keys_id', sa.Integer(), nullable=True),
    sa.Column('strategy_code', sa.String(), nullable=True),
    sa.Column('order_count_type', sa.Integer(), nullable=True),
    sa.Column('dynamic_calculation_type', sa.Integer(), server_default='1', nullable=True),
    sa.Column('strategy_amount', sa.Numeric(), nullable=True),
    sa.Column('position_amount', sa.Numeric(), nullable=True),
    sa.Column('allocation_amount', sa.Numeric(), nullable=True),
    sa.Column('can_use_amount', sa.Numeric(), nullable=True),
    sa.Column('accruing_amounts', sa.Numeric(), nullable=True),
    sa.Column('enable', sa.Integer(), server_default='1', nullable=True),
    sa.Column('days_number', sa.Integer(), nullable=True),
    sa.Column('is_open', sa.Integer(), server_default='0', nullable=True),
    sa.Column('delete_time', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('service_charge', sa.Numeric(), nullable=True),
    sa.Column('lower_limit_of_fees', sa.Numeric(), nullable=True),
    sa.Column('backtest_id', sa.Integer(), nullable=True),
    sa.Column('mock_service_charge', sa.Numeric(), nullable=True),
    sa.Column('mock_lower_limit_of_fees', sa.Numeric(), nullable=True),
    sa.Column('mock_allocation_amount', sa.Numeric(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('is_simulation', sa.Integer(), server_default='0', nullable=True),
    sa.Column('platform', sa.Integer(), server_default='1', nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('order_sysid', sa.String(), nullable=True),
    sa.Column('stock_code', sa.String(), nullable=True),
    sa.Column('traded_volume', sa.Integer(), nullable=True),
    sa.Column('traded_time', sa.Integer(), nullable=True),
    sa.Column('traded_price', sa.Numeric(), nullable=True),
    sa.Column('traded_amount', sa.Numeric(), nullable=True),
    sa.Column('commission', sa.Numeric(), nullable=True),
    sa.Column('order_status', sa.Integer(), nullable=True),
    sa.Column('order_type', sa.Integer(), nullable=True),
    sa.Column('status_msg', sa.String(), nullable=True),
    sa.Column('offset_flag', sa.Integer(), nullable=True),
    sa.Column('orders_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), server_default='0', nullable=True),
    sa.Column('backtest_id', sa.Integer(), nullable=True),
    sa.Column('is_mock', sa.Integer(), server_default='0', nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_is_mock'), 'trades', ['is_mock'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_is_mock'), table_name='trades')
    op.drop_table('trades')
    op.drop_table('tasklist')
    op.drop_table('setting')
    op.drop_index(op.f('ix_ppx_storage_var_key'), table_name='ppx_storage_var')
    op.drop_table('ppx_storage_var')
    op.drop_index(op.f('ix_positions_is_mock'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_orders_is_mock'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('logger')
    op.drop_index(op.f('ix_entrusts_is_mock'), table_name='entrusts')
    op.drop_table('entrusts')
    op.drop_table('data_trade_date_hist')
    op.drop_table('data_table_record')
    op.drop_table('data_st_stocks')
    op.drop_table('data_all_stocks')
    op.drop_table('backtest')
    op.drop_table('account')
    # ### end Alembic commands ###
