"""

Revision ID: a4f715ab4b80
Revises: 0beac3d413f5
Create Date: 2025-05-30 14:11:43.851918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4f715ab4b80'
down_revision = '0beac3d413f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('task_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'task_id')
    # ### end Alembic commands ###
