"""

Revision ID: a5f04056d6dd
Revises: bd9f4edc43f0
Create Date: 2025-06-06 15:03:25.280203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f04056d6dd'
down_revision = 'bd9f4edc43f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasklist', sa.Column('share_secret', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasklist', 'share_secret')
    # ### end Alembic commands ###
