"""

Revision ID: aa39b00cc416
Revises: 070a4abaf019
Create Date: 2025-06-04 15:40:48.699620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa39b00cc416'
down_revision = '070a4abaf019'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest', sa.Column('accruing_amounts', sa.Numeric(), nullable=True))
    op.add_column('tasklist', sa.Column('accruing_amounts', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasklist', 'accruing_amounts')
    op.drop_column('backtest', 'accruing_amounts')
    # ### end Alembic commands ###
