"""

Revision ID: af741b58d30c
Revises: fee48e19d19f
Create Date: 2025-06-09 14:41:00.344566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af741b58d30c'
down_revision = 'fee48e19d19f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logger', sa.Column('task_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logger', 'task_id')
    # ### end Alembic commands ###
