"""

Revision ID: b0ec1d0d11aa
Revises: 4b30d3ff9ca0
Create Date: 2025-06-04 10:02:30.962922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0ec1d0d11aa'
down_revision = '4b30d3ff9ca0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasklist', sa.Column('mock_service_charge', sa.Numeric(), nullable=True))
    op.add_column('tasklist', sa.Column('mock_lower_limit_of_fees', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasklist', 'mock_lower_limit_of_fees')
    op.drop_column('tasklist', 'mock_service_charge')
    # ### end Alembic commands ###
