"""

Revision ID: b43147be6240
Revises: 893f6c585cd2
Create Date: 2025-05-20 17:19:49.603670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b43147be6240'
down_revision = '893f6c585cd2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ppx_storage_var', 'remark2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ppx_storage_var', sa.Column('remark2', sa.VARCHAR(), server_default=sa.text("('')"), nullable=False))
    # ### end Alembic commands ###
