"""

Revision ID: ba7814e60edb
Revises: 0c14bb355caa
Create Date: 2025-06-03 11:56:08.529352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba7814e60edb'
down_revision = '0c14bb355caa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('traded_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'traded_time')
    # ### end Alembic commands ###
