"""

Revision ID: bd9f4edc43f0
Revises: 09f54fab8f5b
Create Date: 2025-06-06 14:59:08.216517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd9f4edc43f0'
down_revision = '09f54fab8f5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasklist', sa.Column('task_type', sa.Integer(), server_default='1', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasklist', 'task_type')
    # ### end Alembic commands ###
