"""

Revision ID: cb83aa7a9d58
Revises: 560b1c57f776
Create Date: 2025-06-17 16:46:16.339825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb83aa7a9d58'
down_revision = '560b1c57f776'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('setting', sa.Column('client_type', sa.Integer(), server_default='1', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('setting', 'client_type')
    # ### end Alembic commands ###
