"""

Revision ID: cf01b55a1307
Revises: ba7814e60edb
Create Date: 2025-06-03 15:09:36.742306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf01b55a1307'
down_revision = 'ba7814e60edb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasklist', sa.Column('dynamic_calculation_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasklist', 'dynamic_calculation_type')
    # ### end Alembic commands ###
