"""${m}

Revision ID: cf8280f1b499
Revises: bb1f7dcbde39
Create Date: 2025-06-26 22:26:01.985841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf8280f1b499'
down_revision = 'bb1f7dcbde39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
