"""

Revision ID: d00d4466cc95
Revises: d0a534f62656
Create Date: 2025-05-31 22:32:17.701351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd00d4466cc95'
down_revision = 'd0a534f62656'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest', sa.Column('name', sa.String(), nullable=True))
    op.add_column('backtest', sa.Column('frequency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest', 'frequency')
    op.drop_column('backtest', 'name')
    # ### end Alembic commands ###
