"""

Revision ID: d0a534f62656
Revises: 84093fc6bb19
Create Date: 2025-05-31 00:47:29.994821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0a534f62656'
down_revision = '84093fc6bb19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entrusts', sa.Column('backtest_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('backtest_id', sa.Integer(), nullable=True))
    op.add_column('positions', sa.Column('backtest_id', sa.Integer(), nullable=True))
    op.add_column('trades', sa.Column('backtest_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'backtest_id')
    op.drop_column('positions', 'backtest_id')
    op.drop_column('orders', 'backtest_id')
    op.drop_column('entrusts', 'backtest_id')
    # ### end Alembic commands ###
