"""

Revision ID: d3a25fd123c4
Revises: 423724d7bf7f
Create Date: 2025-06-17 21:47:24.774678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3a25fd123c4'
down_revision = '423724d7bf7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('setting', sa.Column('ths_client_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('setting', 'ths_client_id')
    # ### end Alembic commands ###
