"""

Revision ID: d5ea964b3b9d
Revises: f91a00207174
Create Date: 2025-06-11 21:56:51.312441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5ea964b3b9d'
down_revision = 'f91a00207174'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest', 'is_simulation')
    op.add_column('tasklist', sa.Column('is_simulation', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasklist', 'is_simulation')
    op.add_column('backtest', sa.Column('is_simulation', sa.INTEGER(), server_default=sa.text("'0'"), nullable=True))
    # ### end Alembic commands ###
