"""

Revision ID: d6609cc360f8
Revises: 99e3e584e08e
Create Date: 2025-06-09 21:03:45.091587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6609cc360f8'
down_revision = '99e3e584e08e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_table_record', 'record_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_table_record', sa.Column('record_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
