"""

Revision ID: dac0eafcee97
Revises: d00d4466cc95
Create Date: 2025-05-31 23:04:12.412912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dac0eafcee97'
down_revision = 'd00d4466cc95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest', sa.Column('initial_capital', sa.Numeric(), nullable=True))
    op.add_column('backtest', sa.Column('lower_limit_of_fees', sa.Numeric(), nullable=True))
    op.drop_column('backtest', 'initial_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest', sa.Column('initial_amount', sa.NUMERIC(), nullable=True))
    op.drop_column('backtest', 'lower_limit_of_fees')
    op.drop_column('backtest', 'initial_capital')
    # ### end Alembic commands ###
