"""

Revision ID: e0c2edd701ce
Revises: 529782e3dade
Create Date: 2025-06-02 17:53:59.260476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0c2edd701ce'
down_revision = '529782e3dade'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('traded_amount', sa.Numeric(), nullable=True))
    op.drop_column('trades', 'price')
    op.drop_column('trades', 'price_type')
    op.drop_column('trades', 'order_volume')
    op.drop_column('trades', 'order_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('order_time', sa.INTEGER(), nullable=True))
    op.add_column('trades', sa.Column('order_volume', sa.INTEGER(), nullable=True))
    op.add_column('trades', sa.Column('price_type', sa.INTEGER(), nullable=True))
    op.add_column('trades', sa.Column('price', sa.NUMERIC(), nullable=True))
    op.drop_column('trades', 'traded_amount')
    # ### end Alembic commands ###
