"""

Revision ID: e4f130d89eb8
Revises: 61f020288394
Create Date: 2025-06-05 10:42:11.133859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f130d89eb8'
down_revision = '61f020288394'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest', sa.Column('can_use_amount', sa.Numeric(), nullable=True))
    op.add_column('tasklist', sa.Column('can_use_amount', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasklist', 'can_use_amount')
    op.drop_column('backtest', 'can_use_amount')
    # ### end Alembic commands ###
