"""

Revision ID: eebf0c1055d1
Revises: 1a94dda4fa31
Create Date: 2025-06-07 10:13:43.324716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eebf0c1055d1'
down_revision = '1a94dda4fa31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasklist', sa.Column('strategy_keys_id', sa.Integer(), nullable=True))
    op.drop_column('tasklist', 'strategy_key_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasklist', sa.Column('strategy_key_id', sa.INTEGER(), nullable=True))
    op.drop_column('tasklist', 'strategy_keys_id')
    # ### end Alembic commands ###
