"""

Revision ID: f91a00207174
Revises: f8a587fd9552
Create Date: 2025-06-11 21:51:28.523366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f91a00207174'
down_revision = 'f8a587fd9552'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest', sa.Column('is_simulation', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest', 'is_simulation')
    # ### end Alembic commands ###
