"""

Revision ID: fa5bf4cff82d
Revises: 
Create Date: 2025-07-07 00:21:13.980009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa5bf4cff82d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasklist', 'platform',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasklist', 'platform',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
