"""

Revision ID: fb407105710b
Revises: eebf0c1055d1
Create Date: 2025-06-08 11:33:13.243192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb407105710b'
down_revision = 'eebf0c1055d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasklist', sa.Column('user_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasklist', 'user_id')
    # ### end Alembic commands ###
