"""

Revision ID: fee48e19d19f
Revises: 2f7dcb98dbdc
Create Date: 2025-06-09 12:39:56.981493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fee48e19d19f'
down_revision = '2f7dcb98dbdc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
